<?xml version="1.0"?>
<?xml-stylesheet type="text/xsl" href="/oma_tabular.xsl"?>
<!DOCTYPE services [
	<!ELEMENT services	(title, description, service+)>
	<!ELEMENT title		(#PCDATA)>
	<!ELEMENT description	(#PCDATA)>
	<!ELEMENT service	(application*)>
	<!ATTLIST service
		typename CDATA	#REQUIRED
	>
	<!ELEMENT application	(#PCDATA)>
	<!ATTLIST application
		name	CDATA	#REQUIRED
		href	CDATA	#REQUIRED
	>
]>
<services>
	<title>Mailsystem Services</title>
	<description>Applications and services on mailservers of HurriKaNe Systems.</description>
	<service typename="Verwaltung">
		<application name="Openmailadmin" href="/openmailadmin/">
			Here you can change your password and create more email addresses for your mailbox.
		</application>
	</service>
	<service typename="Webmailer">
		<application name="IMP aus Horde" href="/horde/imp/">
			The allround webmailer. By Turba you can manage your contacts and by INGO create
			rules for incoming emails as well as create vacation messages.
		</application>
		<application name="RoundCube" href="/roundcube/">
			A leightweight and easy-to-use web 2.0 webmailer.
			Does not support encryption!
		</application>
	</service>
</services>